server:
  port: 38099
  servlet:
    context-path: /notify
spring:
  application:
    name: NotifyServerApplication
  datasource:
    url: jdbc:h2:mem:notifydb
    username: root
    password: sy123.
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
push:
  server:
    port: 38101