/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sy_jnidemo_MyUtil */

#ifndef _Included_com_sy_jnidemo_MyUtil
#define _Included_com_sy_jnidemo_MyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sy_jnidemo_MyUtil
 * Method:    getWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sy_jnidemo_MyUtil_getWord
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
