server:
  port: 38097
  servlet:
    context-path: /shope
spring:
  application:
    name: ShopeApplication
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/sy
    username: root
    password: root.
    hikari:
      pool-name: ShopeDataSourcePool
      minimum-idle: 10
      maximum-pool-size: 60
      max-lifetime: 120000
      auto-commit: false
      idle-timeout: 30000
      connection-timeout: 60000
      connection-test-query: select 1
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      connection-timeout: 1
      read-timeout: 30
mybatis-plus:
  mapper-locations: lasspath:mappers/*.xml
  global-config:
    db-config:
      id-type: ID_WORKER_STR
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: '!@#$SCsNjyHf%$'
  expire: 3600
pay:
  we-chat:
    appId: oodd
    mchId: dd
    key: 'xxxxxxxxxxxxx'
    certPath: static/cert/wxpay/apiclient_cert.p12
    payNotifyUrl: http://xxx.com/wxPay/notify
    refundNotifyUrl: 'a'
socketio:
  # host: 192.168.1.178
  host: 127.0.0.1
  port: 38082
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:38090/eureka/,http://127.0.0.1:38091/eureka/
    # 从eureka 上获取服务列表时间 30
    registry-fetch-interval-seconds: 30
    # 复制实例变化信息到eureka服务器所需要的时间间隔
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: shopeApplication
    #   Eureka服务器在接收到本实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    lease-renewal-interval-in-seconds: 30
    #  eureka客户需要多长时间发送心跳给eureka服务器
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator